modLoader="javafml"
loaderVersion="[37,)"
license="MIT"

[[mods]]
modId="trumpetskeleton"
version="${file.jarVersion}"
displayName="Trumpet Skeleton"
authors="JamiesWhiteShirt (1.16 port by gdude, 1.17 port by Tslat)"
description='''
The sound of trumpets echoes through the night...
'''

[[dependencies.trumpetskeleton]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.trumpetskeleton]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
