modLoader="javafml"
loaderVersion="[31,)"
license="MIT"

[[mods]]
modId="trumpetskeleton"
version="${file.jarVersion}"
displayName="Trumpet Skeleton"

authors="JamiesWhiteShirt (port by gdude2002, adjusted by Tslat)"

description='''
The sound of trumpets echoes through the night...
'''

[[dependencies.trumpetskeleton]]
    modId="forge"
    mandatory=true
    versionRange="[36.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.trumpetskeleton]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"
